version: '3.4'

services:
  controllerServer:
    image: ${DOCKER_REGISTRY-}controllerserver
    environment:
      - WORKSPACE_SERVER_PORT=${WORKSPACE_SERVER_PORT}
      - WORKSPACE_SERVER_URL=${WORKSPACE_SERVER_URL}
    build:
      context: dev/controller
      dockerfile: Dockerfile
    ports:
      - ${CONTROLLER_SERVER_PORT}:80
    volumes:
      - ${PATH_TO_VOLUMES}:/app/volumes

  websocketserver:
    image: ${DOCKER_REGISTRY-}websocketserver
    environment:
      - PATH_TO_CONFIG=./Configuration/config.json
      - PATH_TO_DATA=./Data/
    build:
      context: dev/WebSocketServer
      dockerfile: WebSocketServer/Dockerfile
    ports:
      - ${WORKSPACE_SERVER_PORT}:80
    tty: true
    volumes:
      - ${PATH_TO_VOLUMES}/Configuration:/app/Configuration
      - ${PATH_TO_VOLUMES}/Data:/app/Data

