version: '3.4'

services:
  websocketserver:
    image: ${DOCKER_REGISTRY-}websocketserver
    build:
      context: .
      dockerfile: WebSocketServer/Dockerfile
    ports:
      - '8080:80'
